apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote-app
  labels:
    name: db-service
    app: demo-vote-app
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
     name: postgres-pod
     app: demo-vote-app
