apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  namespace: vote-app
  labels:
    name: redis-pod
    app: demo-vote-app
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
     - containerPort: 6379