apiVersion: v1
kind: Pod
metadata:
  name: vote-app-pod
  namespace: vote-app
  labels:
    name: vote-app-pod
    app: demo-vote-app
spec:
  containers:
  - name: vote-app
    image: dockersamples/examplevotingapp_vote
    ports:
         - containerPort: 80