apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  namespace: vote-app
  labels:
    name: worker-app-pod
    app: demo-vote-app
spec:
  containers:
  - name: worker-app
    image: dockersamples/examplevotingapp_worker